#!/bin/sh

# debootstrap.sh
# A script to deinit all or specific submodules with user permission.

# Get the list of submodules to process. 
# If arguments are provided, use them as the list. 
# Otherwise, process all submodules.
if [ $# -gt 0 ]; then
    SUBMODULES=("$@")
    echo "Specified submodules: ${SUBMODULES[*]}"
else
    SUBMODULES=(binutils-os2 gcc-os2 libc cmake-os2)
    echo "All submodules: ${SUBMODULES[*]}"
fi

# Confirm with the user
echo "This will deinit the following submodules: ${SUBMODULES[*]}"
read -p "Are you sure you want to proceed? (y/N) " confirm

if [[ "$confirm" =~ ^[Yy]$ ]]; then
    for sub in "${SUBMODULES[@]}"; do
        if test -L "$sub" ; then
          sub=$(readlink $sub)
        fi
        echo "Deinitializing $sub..."
        git submodule deinit -f "$sub"
    done
    echo "Done."
else
    echo "Aborted."
    exit 1
fi

