#! /bin/sh

set -e

printlist()
{
  for e in "$@"; do
    echo "    $e"
  done
}

myname=$(basename $0)
mydir=$(dirname $0)

opt_d=false

for p in "$@"; do
  # destdir should be the last
  if [ -n "$destdir" ]; then
    packages=""
    break
  fi

  case "$p" in
    -d)
      opt_d=true
      ;;
    *)
      if $opt_d; then
        destdir="$p"
        opt_d=false
      else
        packages="$packages${packages:+ }$p"
      fi
      ;;
  esac
done

if [ -z "$packages" ] || $opt_d ; then
  echo "Usage: $myname URL_for_ZIP ... [-d destdir]"
  echo
  echo "This will install the ZIPs to destdir."
  echo "If destdir is omitted, destdir will be i686-pc-os2-emx of" \
       "the parent dir of"
  echo "the dir where $myname is. That is, dir/../i686-pc-os2-emx."
  exit 1
fi

# assume we're in /opt/os2emx/bin directory
prefix=$mydir/..
target=i686-pc-os2-emx
targetprefix=${destdir:-"$prefix/$target"}

: ${CURL:=curl -sSfL}
: ${UNZIP:=unzip}
: ${MKDIR_P:=mkdir -p}
: ${CP:=cp}
: ${RM:=rm}

zipdir="$myname.zip.dir"

curlopts=""
for zipurl in $packages; do
  curlopts="$curlopts${curlopts:+ }-O $zipurl"
done

echo "Downloading the ZIPs..."
printlist $packages
zips=$($CURL -J -w "%{filename_effective}\n" $curlopts)

echo "Unzipping the ZIPs..."
printlist $zips
zipprefixes=""
for zip in $zips; do
  $UNZIP -u "$zip" -d "$zipdir"

  # find prefix of the ZIP
  while read -r s d t p; do
    case "$p" in
      */bin/ | */include/ | */lib/ | */lib64/ | */share/)
        zipprefixes="$zipprefixes${zipprefixes:+ }/${p%/*/}"
        break
        ;;
    esac
  done << EOF
$($UNZIP -qql "$zip")
EOF
done

echo "Installing the unzipped file(s) into $targetprefix..."
$MKDIR_P "$targetprefix"
for zipprefix in $zipprefixes; do
  for d in "$zipdir$zipprefix"/* ; do
    if [ -d "$d" ] ; then
      $CP -a "$d" "$targetprefix" || break
    fi
  done
done

echo "Cleaning up..."
$RM -rf $zips "$zipdir"
