#! /bin/sh

myname=$(basename $0)
mydir=$(dirname $0)

package="$1"
destdir="$2"

if [ -z "$package" ] ; then
  echo "Usage: $myname package[_oc00[.zip]] [destdir]"
  echo
  echo "This will install package[_oc00[.zip] to destdir."
  echo "If destdir is omitted, destdir will be i686-pc-os2-emx of" \
       "the parent dir of"
  echo "the dir where $myname is. That is, dir/../i686-pc-os2-emx."
  exit 1
fi

# assume we're in /opt/os2emx/bin directory
prefix=$mydir/..
target=i686-pc-os2-emx
targetprefix=${destdir:-"$prefix/$target"}

: ${WGET:=wget}
: ${UNZIP:=unzip}
: ${MKDIR_P:=mkdir -p}
: ${CP:=cp}
: ${RM:=rm}

zipurl="https://rpm.netlabs.org/release/00/zip"

# normalize package
package=${package%.zip}
package=${package%_oc00}
package="${package}_oc00.zip"

$WGET "$zipurl/$package" &&
  $UNZIP -u "$package" -d "$package.dir" &&
  $MKDIR_P "$targetprefix" &&
  for d in "$package.dir/@unixroot/usr"/* ; do
    $CP -a "$d" "$targetprefix" || break
  done

$RM -rf "$package.dir" "$package"
