name: CI Build and Test

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'cross-os2emx.txt'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '.github/FUNDING.yml'
      - '.github/dependabot.yml'

    tags-ignore:
      - '**'

  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'cross-os2emx.txt'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '.github/FUNDING.yml'
      - '.github/dependabot.yml'

jobs:
  call-ci-main:
    uses: ./.github/workflows/ci-main.yml
    permissions:
      contents: write
