name: linux-x64

on:
  push:
    paths-ignore:
      - '**.md'
      - 'cross-os2emx.txt'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '.github/FUNDING.yml'
      - '.github/dependabot.yml'

  pull_request:
    paths-ignore:
      - '**.md'
      - 'cross-os2emx.txt'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '.github/FUNDING.yml'
      - '.github/dependabot.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext autopoint

      - name: Set up git account
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set MAKEFLAGS
        run: echo "MAKEFLAGS=-j$(($(nproc) + 1))" >> $GITHUB_ENV

      - name: Bootstrap
        run: ./bootstrap

      - name: Build
        run: make

      - name: Install
        run: make install

      - name: Test
        run: make test

      - name: Dist
        run: make dist
