name: macos-arm64

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!cross-os2emx.txt'

  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!cross-os2emx.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: gerlero/brew-install@v1
        with:
          packages: coreutils texinfo autoconf
          cache: false

      - name: Set up git account
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set MAKEFLAGS and path
        run: |
          echo "MAKEFLAGS=-j$(($(nproc) + 1))" >> $GITHUB_ENV
          echo "PATH=$(echo /opt/homebrew/Cellar/coreutils/*/libexec/gnubin):${PATH}" >> $GITHUB_ENV

      - name: Bootstrap
        run: ./bootstrap

      - name: Build
        run: make

      - name: Install
        run: make install

#      - name: Test
#        run: make test

      - name: Dist
        run: make dist

      - name: Rename package
        run: |
          version="$(git describe --abbrev=0)"
          mv cross-os2emx-$version.tar.gz cross-os2emx-arm64-$version.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Build-${{ github.run_id }}
          path: cross-os2emx-*.tar.gz
          overwrite: true

